### ISSUE TITLE
Release 0.7 to AMO

### ISSUE THREAD

**Issue by ath0mas** [gmail-manager-community/gmail-manager-community#12]
Firefox will force [extension signing](https://wiki.mozilla.org/Addons/Extension_Signing) soon:

```
* Firefox 40-42: warn about signatures
* Firefox 43: signature enforcement can be disabled with a preference
* Firefox 44: Release and Beta versions do not allow unsigned extensions
* ESR: preference to disable enforcement
```

So, important [Firefox milestones](https://wiki.mozilla.org/RapidRelease/Calendar) are _version 43_ (**2015-12-15**) and ultimately _version 44_ (**2016-01-26**)

**Comment by ath0mas** [comment]
Next milestone is [0.7-alpha.3](https://github.com/gmail-manager-community/gmail-manager-community/milestones/0.7-alpha.3):
* see **0.7-alpha.2** "issues" discussed in #2 to give help or test, please

**Comment by ath0mas** [comment]
Development branch for version **0.7** is `0.7-dev`.
We should create Pull Requests to iterate with new features on this way to AMO.

[Add-on validator](https://addons.mozilla.org/en-US/developers/addon/validate) can be used to detect warnings on demand

**Comment by tigerdencafe** [comment]
looking forward to version 7 :) thank you

**Comment by ath0mas** [comment]
[0.7-beta.1](https://github.com/gmail-manager-community/gmail-manager-community/releases/tag/0.7-beta.1) available
... and happy to see it landed well in [AMO](https://addons.mozilla.org/firefox/addon/gmail-manager-community/) too :yum: 

Next steps for _beta.2_ (_release_?):
- some additional minor changes & clean
- review "_migration_" process from **NG** to **community**

@iHastr any new translations to update before **0.7** release?

**Comment by wimh** [comment]
Looks like the URL should be https://addons.mozilla.org/en-US/firefox/addon/gmail-manager-community/.

**Comment by M3Rocket** [comment]
Been running beta-1 in FF 42 since it was made available. Working well! Nice job @ath0mas!

**Comment by ath0mas** [comment]
@wimh fixed URL, thx
Thx @M3Rocket

**Comment by iHastr** [comment]
@ath0mas 
Please change in RU locale the following string in the file **gmanager.dtd**:
`<!ENTITY options-help-forked-from "Forked from:">`
change to
`<!ENTITY options-help-forked-from "Форк из:">`

Can you add my nickname to the list of "Contributors" in the file
**\content\options\pages\help.xul** :question:
`<menuitem label="iHastr (RU)"/>`
But I'm not BabelZilla translator in this project :pensive:
That's all. Thanks!
