### ISSUE TITLE
Version 0.7-alpha.2 warnings in AMO validation

### ISSUE THREAD

**Issue by ath0mas** [gmail-manager-community/gmail-manager-community#2]
Gmail Manager-community 0.7-alpha.2 validation check from AMO on October 21 shows many warnings:

~~1 error: "Duplicate UUID found"~~ (I was using wrong account to send file)

```
- notes: 1 for General
- warnings: 2 for Security + 21 for Extensions + 38 for Localization
```

**Comment by ath0mas** [comment]
[Add-on validator](https://addons.mozilla.org/en-US/developers/addon/validate) can be used to detect warnings on demand: review messages from #1 are more explicit now :grin: ; will be easier to target and fix for 0.7-alpha.3 :dart:

**Comment by jrddyson** [comment]
Alexis, thank you for doing this next important step, the AMO process :+1:

**Comment by ath0mas** [comment]
Work on 0.7 reset to get back to a cleaner branching model (#11): going back to parent issue #12
