### ISSUE TITLE
Register on BabelZilla

### ISSUE THREAD

**Issue by ath0mas** [gmail-manager-community/gmail-manager-community#21]
Register on [BabelZilla](https://www.babelzilla.org/) to have more localizations for extension

**Comment by ath0mas** [comment]
Unable to register on https://www.babelzilla.org at the moment: "Something is wrong with your supplied details."
waiting for BabelZilla to help me with that

**Comment by ath0mas** [comment]
Registered and uploaded current version: 100% (183 strings) for 39 locales

Visit https://www.babelzilla.org/forum/index.php?showtopic=7686 and contribute in WTS for new translations and future updates.

**Comment by ath0mas** [comment]
Hi @HrantOhanyan, would you mind adding Armenian locale, like you asked in [GM-NG issue #50](https://github.com/nedwidek/firefox-gmail-manager-ng/issues/50)?

**Comment by HrantOhanyan** [comment]
Hi Alexis
Sure!
Please let me know, when you will release a new version.
Thanks.
............
_Best Regards, 2015
Hrant »»» http://haysoft.org_

Alexis THOMAS-ը գրել է.
