### ISSUE TITLE
Randomly Disappearing from Addon-Bar

### ISSUE THREAD

**Issue by jschamba** [gmail-manager-community/gmail-manager-community#22]
I seem to be having an issue where it will randomly disappear from the addon-bar.  I only get it back by either restarting Firefox or going to Add-ons -> Gmail Manager-community -> Options -> Clicking OK.  All my accounts are set to Display in toolbar: addon-bar.  Happens multiple times during the day.

**Comment by gmng** [comment]
Choose GiT-addon-bar instead of "addon-bar"

**Comment by jschamba** [comment]
So I have to install another add-on for it to not disappear?

I actually prefer it to be in the same location as all my other add-ons instead of at the bottom of the browser.

**Comment by gmng** [comment]
I use The Addon Bar (restored).
https://addons.mozilla.org/hu/firefox/addon/the-addon-bar/?src=userprofile

**Comment by jschamba** [comment]
Sure, but shouldn't it be able to work correct without the need for an additional addon?

**Comment by gmng** [comment]
Mozilla disabled the addon bar in a previous version of FF and this add on was the only solution at that time to restore it. I use this add on anyway.

**Comment by jschamba** [comment]
I'm aware they removed the addon bar at the bottom of FF, but they essentially moved it up to the top right of the browser.  Before the changes to Gmail which made Gmail Manager broken, I never had a problem with the addon randomly disappearing.  Is it possible there is a bug in this fork that is causing it to disappear?

**Comment by ath0mas** [comment]
@jschamba which Firefox and add-on versions? one or more email accounts?
Settings in Toolbar tab for "Display placement" and "Selected account"?

**Comment by jschamba** [comment]
FF 42.0
2 Accounts
Display in toolbar:  addon-bar
Selected account - Hide alias from being displayed

**Comment by ath0mas** [comment]
Please see #5: seems that "nav-bar" is a _solution_?

**Comment by ath0mas** [comment]
@jschamba is it ok now? using "nav-bar"?

**Comment by jschamba** [comment]
Yes it doesn't disappear from "nav-bar", but would be nice to get it working right with "addon-bar" as well if that's possible.  Thanks for the help.

**Comment by ath0mas** [comment]
Fine ;)
Sure. We'll try to understand why and make that more _stable_

**Comment by jschamba** [comment]
Big thanks for keeping this addon alive, it is absolutely the best gmail addon for Firefox without question.

**Comment by damienfournier** [comment]
Maybe we should remove the "addon-bar" option in the dropdown list, since it doesn't exists anymore ?

**Comment by ath0mas** [comment]
List of toolbars is dynamic : https://github.com/gmail-manager-community/gmail-manager-community/blob/develop/chrome/content/utils/toolbars.js#L19

So "addon-bar" appears to be a valid toolbar element from Firefox itself

Don't know yet how to deal with it properly... which value to set as default? any contribution or idea on how to _fix_ issue when "addon-bar" is selected? clear explanation if it can not work with it at all, before hardcoding the removal of this value?

**Comment by damienfournier** [comment]
It doesn't work with the addon-bar, the position resets each time Firefox boots.
I think we can remove the addon-bar from the list just by checking its name (hardcoding is bad, I know, but it works).

I'd put nav-bar by default, since it always works (top right).

**Comment by ath0mas** [comment]
Fine :smiley: 

Indeed, inspecting browser xul, we can see that addon-bar is like _hidden_:

```
#addon-bar {
    ...
    height: 0 !important;
}
```

So, commit to come will replace all instances of "addon-bar" with "nav-bar" in code.
And "addon-bar" will be skipped when reading toolbars from browser.ownerDocument
