### ISSUE TITLE
Update for German locale

### ISSUE THREAD

**Issue by Endor8** [gmail-manager-community/gmail-manager-community#23]
Hi.
I updated the German locale:
Here the two changed files:
https://dl.dropbox.com/u/15467633/Firefox/Sonstiges/gmanager.dtd
https://dl.dropbox.com/u/15467633/Firefox/Sonstiges/gmanager.properties

Cheers
Endor

**Comment by ath0mas** [comment]
Commit f0591d7
Thanks @Endor8
