### ISSUE TITLE
Email Notifications not working on one of my accounts.

### ISSUE THREAD

**Issue by AMDZen** [gmail-manager-community/gmail-manager-community#26]
I have a similar issue as what is listed here, however I have checked and I do NOT have 2 step verification enabled on my account so I thought perhaps I should start my own thread.  I have 8 email addresses, 7 of which are working fine using this extension (which is awesome BTW) and one that won't show new email counts at all.

All of the accounts show the same thing when I hover over it with a mouse, besides the one not working.  The 7 correctly working accounts would show "Inbox has X unread messages" on the top line, then spam messages, then space.

On the account that is NOT working, it first shows "(null) important unread messages", then "inbox has 0 unread messages" (again this is always zero even when there are unread messages) and then the same as above.  I have checked all of my settings trying to figure out what the issue is, I have deleted this account several times and recreated it to see if that would work and nothing has worked, and nothing appears out of the ordinary for this account versus the others.  I have all the same settings about it marking "important" messages, however this account simply refuses to show the unread messages notifications.

Of course this account that isn't working is my main and most important account, so any help would be greatly appreciated.  Thanks

**Comment by ath0mas** [comment]
@AMDZen
- any error log in Browser Console (Ctrl+Shift+J)? when, from addon right click menu, disconnect account, then reconnect it. Something like that?

```
gmanager: (***@gmail.com) space used = 000
gmanager: (***@gmail.com) total space = 11111
gmanager: (***@gmail.com) percent used = 2
gmanager: (***@gmail.com) Error getting the unread counts: SyntaxError: JSON.parse: expected ',' or ']' after array element at line 1 column 456 of the JSON data
```
- any "special" char, like `,,`, `[,` or `,]` in your labels or unread mails subject/body?

**Comment by ath0mas** [comment]
0.7.1.1 released today ; can you check if notifications seem to work better?

**Comment by pvkid** [comment]
where is 0.7.1.1 available to download?

**Comment by ath0mas** [comment]
@pvkid if addon already installed, check for updates in Firefox Add-ons Manager ; else install from [AMO](https://addons.mozilla.org/en-US/firefox/addon/gmail-manager-community/)

**Comment by AMDZen** [comment]
This issue was never fixed for me BTW.  Still only one account that never shows i have unread messages.  Maybe screen shots will help?  The first one here

http://i.imgur.com/BWrMSnU.jpg

Is where I sent myself 2 emails.  First with just amd in the subject and nothing showed.  Then I tried with ,,, in the subject like it seemed (above) someone wanted me to try?  Or that it causes problems?  So I tried the first email without that.  You can sse the null in the first screen shot I described and not in this one

http://imgur.com/t9ENLTq.jpg

Where I sent myself an email to another account that works fine.  Like I said, all my accounts work fine except for one.  No ryhme or reason as far as I can tell.  Yes I have tried to logout of this account and back in, yes I have tried to logout of ALL accounts and back in.  Nothing seemed to help

Maybe this is what you needed to see error wise? 

http://imgur.com/dDdyV2o.jpg

When I click on it it gives me this line highlighted

"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.Ye.setRequestHeader(b,a)},this);this.w1&&(this.Ye.responseType=this.w1);"withCredentials"in this.Ye&&this.Ye.withCredentials!==this.HI&&(this.Ye.withCredentials=this.HI);try{Ufa(this),0<this.Cea&&((this.i1b=Vfa(this.Ye))?(this.Ye.timeout=this.Cea,this.Ye.ontimeout=h(this.Yu,this)):this.Dz=yd(this.Yu,this.Cea,this)),this.Dca=!0,this.Ye.send(a),this.Dca=!1}catch(g){this.Ep(5,g)}};
