### ISSUE TITLE
Add-on not logging in since Firefox 45.0 update

### ISSUE THREAD

**Issue by jrddyson** [gmail-manager-community/gmail-manager-community#27]
Click ok on the login prompt and password prompt returns.  Re-entering the password does not help.  This has only happened since Firefox updated to 45.0

**Comment by ath0mas** [comment]
Blocking issue for me too :worried: 
Please anybody's help welcomed to go over those new issues since Firefox 45 release:exclamation::anger:

**Comment by ath0mas** [comment]
No error logged inside browser console, in FF45
I will check in Firefox 44 later to see if addon is still working fine...

**"community"**: any investigation/clue by your side to share? linked to FF45 changes you think? or GMail API?

**Comment by ath0mas** [comment]
Logging in still works in Firefox 44

**Comment by skrivskithar** [comment]
I'm on FF 45.0.1 and it's still loging in and out. The only issue I have is the dragging one mentioned on another thread here.

**Comment by jrddyson** [comment]
I think I've made a error here, there is no bug.  For me, **Privacy Badger** was causing the issue with logging in.  In the settings for it I've had to allow cookies for **accounts.google.com** and now the accounts can login again.
