### ISSUE TITLE
Password not working since ff 45

### ISSUE THREAD

**Issue by kristjan72** [gmail-manager-community/gmail-manager-community#30]
Gmail manager community wont accept the correct password for any of my four gmail accounts since upgrading to FireFox 45. Going back to 44 fixes it.

**Comment by justposted** [comment]
Same here. Installed v44 from here (http://ftp.mozilla.org/pub/firefox/releases/44.0b9/) and turned off auto-update for now.

**Comment by ath0mas** [comment]
Have you seen #27 ? Are you using Privacy Badger?

**Comment by kristjan72** [comment]
ath0mas no I hadnt seen that. It seems this was the problem and its working now. Thanks!
