### ISSUE TITLE
"Jumpy" snippets window

### ISSUE THREAD

**Issue by ath0mas** [gmail-manager-community/gmail-manager-community#32]
As a follow-up to #29 fix, snippets window has shorter open and close phases and feels like "jumpy" compared to what should be seen before Firefox 45

**Comment by seaders** [comment]
Give the newest PR a try, it seems like the browser restriction only hits resizeTo / resizeBy, not moveTo / moveBy, so if you move the dialog off-screen, then tween it on, then off, it's back to how it was.

**Comment by M3Rocket** [comment]
Just tested the PR https://github.com/seaders/gmail-manager-community/commit/9ba8250a5004eb82ebdc76dd08bee73270d3ca8c. Looks good and smooth to me now. Thanx for improving this!

**Comment by M3Rocket** [comment]
This can be closed now I think.

**Comment by ath0mas** [comment]
I'll try to take time next week to review and merge @seaders PRs, so that we can close this issue

**Comment by ath0mas** [comment]
PR #33 merged
