### ISSUE TITLE
Problem displaying snippets #2

### ISSUE THREAD

**Issue by iHastr** [gmail-manager-community/gmail-manager-community#39]
A few days ago in one of my accounts no longer show snippets. Snippet window says "The account does not have snippets to display" even when there are new and unread messages.
Problem is exactly like here: https://github.com/gmail-manager-community/gmail-manager-community/issues/36
Why is this happening and how to fix it?

**Comment by M3Rocket** [comment]
As in https://github.com/gmail-manager-community/gmail-manager-community/issues/36, try changing the Inbox type and report back here. 

For me, the problem cleared up by itself after a few days and I was able to change my Inbox type back to normal. I think this might be Google-related?

**Comment by iHastr** [comment]
I change the Inbox Type from Default to Priority. But snippets are visible only in mode "No snippets - Show subject only". Only the subject is shown and not the snippet of the message.

After 2 days I switched back mode "Show snippets - Show snippets of the message" and now snippets seen normally only for "Priority inbox". If I switch to "Default", snippets are not visible. But if again switch to mode "No snippets - Show subject only", the snippets are visible with subject only.

As a result, in the "Priority inbox" snippets work fine.
In "Default" work only "No snippets - Show subject only".
I don't know how to make full snippets for "Default".

**Comment by M3Rocket** [comment]
Yep--about the same thing happened to me. Then magically in a few days, snippets will fully work again in Default mode. At least that's what I discovered.

**Comment by iHastr** [comment]
Today magically everything works fine in Default mode! Strange and mysterious Google.

**Comment by ath0mas** [comment]
0.7.1.1 released today, and fixes possible broken counts/snippets with `,,`, `[,` or `,]` in your labels or unread mails subject/body
Think it could have been the cause of your issues?
