### ISSUE TITLE
Login Credentials Not Saving

### ISSUE THREAD

**Issue by SeberHusky** [gmail-manager-community/gmail-manager-community#41]
I enter in all my logins, click OK, and then it immediately deletes them and its reset or never saved. Cannot save logins.

**Comment by ath0mas** [comment]
Do you still face this issue?
Versions of OS, Firefox and GMM?

**Comment by SeberHusky** [comment]
It's been fixed. No longer an issue. It fixed itself overnight sometime last month I don't know how.

**Comment by ath0mas** [comment]
OK fine
