### ISSUE TITLE
Gmail account , Google says there's something "unusual"

### ISSUE THREAD

**Issue by Endor8** [gmail-manager-community/gmail-manager-community#42]
There appears to be a new problem with Gmail Manager.  Every time I try to open my Gmail account by clicking the Gmail Manager icon, Google says there's something "unusual" about the way I'm logging it, and I have to verify through a text message, etc. even if I'm already logged in! Anyway it is actually not possible to open Gmail accounts by clicking on the Gmail Manager icon. I think Google has changed something 
today. I hope it will be possible to fix this.

**Comment by bacon-cheeseburger** [comment]
I'm having the exact same problem. I can login manually by going to gmail.com and entering my username/password. But, if I try to login by clicking an account from Gmail Manager, I get "Google couldn't verify it's you, so you can't sign in to this account right now." The strange thing is that Gmail Manager does seem to be able to pull the correct unread counts.

**Comment by peekpeekpeekpeek** [comment]
Same problem. If I just open Gmail manually, no problem, but if I click on Gmail Manager to open Gmail I get the warning and it requires me to get security code via Phone.

**Comment by SeberHusky** [comment]
I have this problem too!  I can sign in fine from Google homepage but it gives me trouble when trying to access my inbox via the addon.

I am glad I'm not the only one!  I was so panicked!

**Comment by skrivskithar** [comment]
+1, same problem, last FF version.

**Comment by BumpShot** [comment]
Mine is doing it too. Need to re-verify   every login.
I'm using Gmail Checker.( Temp ) It works.
It has a option to " Remember the Cookies"  for each account. maybe that helps. IDK

P.s. Can you add a option to show the password to my Email accounts. 
      Maybe just one master password to see the password for each account.

**Comment by bacon-cheeseburger** [comment]
@BumpShot: You can already see them, just go into Firefox settings->security->saved logins->show passwords.

**Comment by BumpShot** [comment]
@bacon-cheeseburger  Mine does not catch passwords. I use Keepass ( with Keefox ).  It locks out Browser password catcher. I'll Try turning off Keepass and see if it works. Thanks.

**Comment by pcf1** [comment]
Hi,

Same issue started today:
Firefox v48.0.1,
Gmail Manager-community 0.7.1.1

As Endor8 described:
Every time I open my Gmail account by clicking Gmail Manager's icon, the following page is being displayed:
![gmailerror](https://cloud.githubusercontent.com/assets/12914625/17829518/b78bdd54-66b9-11e6-9650-a29a6c71ba04.png)

This now happens every time I switched between accounts by clicking Gmail Manager's icon or if I close Firefox, launch it back up and click Gmail Manager's icon once more.

Help is appreciated.

**Comment by Endor8** [comment]
Yes it is exactly like here. It starts yesterday around 10,00 clock UTC in Firefox 48.0
Later I updated Firefox to 48.0.1 but nothing has changed.  I hope someone is able to fix this as soon as possible.

**Comment by tydeus** [comment]
After you click on the gmail manager icon to open mail and you get the 'verify it's you' dialog if you just click the 'use a different account'  then click on your normal account it will log you right in without verifying anything until there's some sort of fix available.

**Comment by piaccazero** [comment]
FF 47.0 Gmail Manager 0.7.1.1 and the one before. Number of unread messages appears when hovering over icon but clicking it redirects to log in page.

**Comment by M3Rocket** [comment]
Google must have changed something with GMail login redirects. I'm on FF ESR 45.3 and GM 0.7.1.1 and this is happening to me as well. If I open a new tab or window and type gmail.com directly in the URL, it works fine without the security prompt.

**Comment by pcf1** [comment]
> After you click on the gmail manager icon to open mail and you get the 'verify it's you' dialog if you just click the 'use a different account' then click on your normal account it will log you right in without verifying anything until there's some sort of fix available.

Thanks, tydeus.
That temporary workaround is nice!

**Comment by seaders** [comment]
This minor nightmare has now passed for me, I'm assuming Google did something bad that wrecked a lot of peoples heads, which they've since reverted.  Long live Gmail Manager Community!

**Comment by MickBim** [comment]
Same here, it's working like before :)

**Comment by mDisna** [comment]
There still seems to be an issue. While I do not get the "unusual" notification anymore, every time I restart the browser and click on an account I need to enter in my password. Once the password has been entered, I can then switch to that account for the duration of my session.

**Comment by Endor8** [comment]
Yes the basic issue is still there. You can not login directly to you google account 
by click the toolbarbutton. It opens only the usual google accounts site, were
you con login manually. But this site has nothing to do with Gmail Manager Add-on.
With Gmail Checker Add-on it is identically . I think google require now this method
for login.

**Comment by BumpShot** [comment]
Google has fixed the security warnings 

Gmail Checker  works. I have 15 accounts. Gmail checker login to all my accounts. one click. Been using this as a backup, since the Gmail Manger problem. It still works. It never stopped working. ( I just like the layout of GM better)

On Gmail Checker ( You must Tick " Remember Login Cookies " )

Gmail Manager is still not a one clicking into the accounts option. It brings you to the login screen with the account filled in. click the page, you have to put in the password for that account.
You must do that to all the accounts Up To 10 accounts.

Google has changed it so that it stores 10 account password. After that it ask you to Sign OUT of all account to see the 11th account. 

You need to re-sign in, if you close the browser.

**Comment by bacon-cheeseburger** [comment]
@BumpShot 
This new change Google has made sucks. I'm considering just registering my own domain and subscribing to a mail host that actually respects privacy. Getting sick of all the stupid `something is unusual about the way you're logging in` crap. 1) NO. I closed Firefox and loaded IE. That's not unusual. 2) Stop trying to use IP location, it DO NOT WORK for people with dynamic ips and ISP's who rotate them often. I'm not a hacker, I just have a stupid ISP.

Sorry, this isn't where I should be ranting. So yeah, hopefully Gmail Manager will get fixed and one-click login will be restored.

**Comment by Endor8** [comment]
Yes lets hope that this can and will be fixed as soon as possible.
Cheers

Endor

**Comment by BumpShot** [comment]
Is This add-on project dead? no one to fix it?

**Comment by SeberHusky** [comment]
@BumpShot 

The problem has fixed itself, rather Google fixed it. And no this is not dead. The last update was 28 days ago.

**Comment by BumpShot** [comment]
@SeberHusky 

It is not fixed.  You can still not 1 Click in to an account. Like how it use to.

Yes, Google has fixed the Verify account page.  

But GM is still broke. It  still make you login in with User Name/Password for each account.
( And yes, google does store User/password for up to 10 accounts until you Restart your computer/browser.)

**Comment by SeberHusky** [comment]
@BumpShot 

I can. It's a problem on your end. Clear your cookies and browser cache. And tell the addon to auto log in on startup. You have something that is deleting your cookies, because I never have to log into my google account, its always signed in.

**Comment by mDisna** [comment]
No, it's a problem with GM or Google because I have the same issue and I'm not tech illiterate. I can't switch to accounts using one click, and I have to log into each one.

I want Gmail Manager to log in for me, I don't want to have to manually sign into all my accounts each time I open my browser, or have to navigate to gmail.com and switch accounts from there. That's the whole point of having this add on.

I also don't want to have my security compromised by having persistent cookies keeping me logged in after I close my browser.

**Comment by BumpShot** [comment]
@SeberHusky 
You have Google saving your Passwords. That is how you are doing the one click. And that only works up to 10 accounts. If you have 11 or more accounts it will not work.

At this point, GM is not lodging you in . it is just taking you to the URL below. Not Safe.

When google save your passwords. Anyone can go to this address " https://mail.google.com/mail/u/? " on your computer.  And then Just change the " ? " to 0-9 to access all you accounts. You could just make shortcuts, then. If that is all you needed.

GM when working , was able to do more that 10 accounts And login to the accounts with out saving the passwords in the browser.

Just like how " Gmail Checker" still does now.  They must both login differently .
Don't Say just use GC. ( like I said before, I like the Layout of GM way better than the GC add-on. )

Hope it gets fixed soon. Maybe Alexis ( ath0mas) is on Vacation.

**Comment by Endor8** [comment]
At moment Gmail Manager is not able to log in, or check for new E-Mails.
Open the account by click on toolbarbutton also not works.
So there is definitely one ore more issue and needs to be fixed. 
I tested it in a new profile but noting changes.

**Comment by bacon-cheeseburger** [comment]
I'm having that problem too Endor8, it's not just you.

**Comment by Endor8** [comment]
The problem is only, that nobody cares about fixing this.
The issue is there, confirmed but nothing happens.
Cheers
Endor

**Comment by MiK-79** [comment]
Hello!
I have the problem already since the last update of GMC. I am really anoyed... Why does it takes such a long time for an update which fixes this error. My parents and I have this problems for weeks...
Sorry for my frustrated posting, I had been happy with this addon for such a long time ;-)
Best regards

**Comment by damienfournier** [comment]
> Why does it takes such a long time for an update which fixes this error. My parents and I have this problems for weeks...

Maybe because this free addon is maintained by volunteers who didn't write the original code, who are not plugin developers and just tried to debug it, and who don't know if it's fixable this time... 

So whining at them isn't helping... 
You want to help ? Help them debug this problem... like we did there: https://github.com/gmail-manager-community/gmail-manager-community/issues/4

**Comment by klubaz** [comment]
gmail-manager-community has been broken for 3 weeks... is it dead ?

**Comment by bacon-cheeseburger** [comment]
I'm sure if anyone was around who had the knowledge to fix it, they would. Unfortunately Gmail Manager has a lot more users than coders. Hopefully it will be fixed though.

**Comment by ath0mas** [comment]
Can you confirm current situation?
- original issue about security/verification warnings is over
- connection, counters, snippets are working fine
- :warning: 1-click auto connect does not work anymore, instead force manual login from Google account page

**Comment by ecc29** [comment]
Yes, auto connect problem is still there. It looks like gmail login system changes a lot recently. When I tried X-notifier, I noticed that I can login to two different gmail accounts simultaneously. This was not allowed before.

**Comment by Endor8** [comment]
I can confirm this. Auto connect problem is still there.
Any thing else works fine.

**Comment by bacon-cheeseburger** [comment]
I can also confirm that everything seems to be working except 1-click auto-connect. Gmail Checker (2.6.6) has the same feature (called "open mailbox") and it still works in that plugin. I don't know what they do differently than Gmail Manager.

**Comment by internero** [comment]
We need to understant what URL and which parameters Gmail Manager and Gmail
Checker are using for this feature.

I think Gmail Manager is using and old (too old) URL and/or parameters that
Google have discontinued.

internero@gmail.com

**Comment by ecc29** [comment]
Gmail Checker v2.6.6 was more than one year ago. It's not new either. If Gmail Checker still works even though google changed something recently, maybe the login part in Gmail Manager need some rework. Actually, as I remember, this is not the first time Gmail Manager stuct because of login problems.

**Comment by ath0mas** [comment]
No more "Google Couldn't sign you in" issue
See #45 for broken **1-click auto-connect**
