### ISSUE TITLE
"Google Couldn't sign you in"

### ISSUE THREAD

**Issue by Catalyst2012** [gmail-manager-community/gmail-manager-community#43]
From Gmail Manager-community 0.7.1.1 - I had no issues logging in any of multiple Gmail accounts (one at a time) up to and including Aug 18/2016. I did not try on 8/19. This started suddenly in both ESR 45.3.0 and Unbranded 48.0. I don't use Privacy Badger.

Starting on 8/20, Gmail Manager-community still reports new emails per account, but I cannot log in to any of the accounts by clicking on the email Alias in the Status Bar as I have always done in the past. Instead, I get [this page](https://accounts.google.com/signin/rejected?hl=en&rrk=2&ard=AHwGkRlg77my2JM9VwC2FE8vhFJMGvH2xOqIArimok1Mds0FY6FfknEkuoWw8iBlte1fU0U56K9XFM7PGM7iGXnJI8PuUFFevs3Rk72OkxLV_T2YUKrhLkxf6AQCOfzInCZEz_HqYhMbMvvQnjvKsv-fLwNXnbLTVMZWECDI3NtoSIp5XQ7FjSZDxakoOPe5nSuHgAfhU-oew0s91fNFWlbt9igDA1J6T9ZQr3CUQG37uA_bBO8NAEu5tRm28NHIOs77OFv0IlOD): 

"Google Couldn't sign you in"

"Google couldn't verify it's you, so you can't sign in to this account right now.
Try again later or use Account Recovery for help."

If from GM-community I Logout All accounts, then manually type www.gmail.com and log in to any of the failed accounts, I can get into that gmail account.

I have no idea why but suspect some new "Google security scheme" perhaps not allowing full login from Gmail Manager-community?
![gm-c google](https://cloud.githubusercontent.com/assets/2553925/17834228/fd8c5122-66ea-11e6-8c7e-3e1ba288fba3.png)

**Comment by seaders** [comment]
Yeah, I'm getting this as well.  Google looks like it's being an ass, and changed something security related.  I basically got locked out of one of the accounts all together, and eventually when I got back in after recovering the account, I had 20 plus warnings from google about "Someone's got your password" with locations attached to just where I've been for the last few days :/

**Comment by Catalyst2012** [comment]
If I choose Recovery, Google asks me when I set up the account. It was somewhere around 12 years ago. I have more than one account. I'm very good about deleting old emails, so how in the world am I supposed to remember the exact time of all my email accounts. This Google security hurts no one except the true account owner.

I travel and sometimes I use a Free internet access terminal outside my country.  Google falsely assumes "someone has my password". When I finally get in to my account, I always confirm it was me. Google doesn't listen.

**Comment by BumpShot** [comment]
@Catalyst2012 

Try closing your browser. Then just go to " gmail.com" and log in

**Comment by Catalyst2012** [comment]
@BumpShot
Thanks. No need to close browser. Instead, in Gmail-manager-community just Logout of the account you want (which defeats using it) and then go to "gmail.com". You may need to delete history.

**Comment by ath0mas** [comment]
Do you still get to this page "Google Couldn't sign you in"?
I suggest to close this issue, and concentrate on #42 for problem to directly open account when clicking Alias in Status Bar. Right for you?

**Comment by Catalyst2012** [comment]
Thank you!
No, I'm not getting it anymore. YES,  #42
https://github.com/gmail-manager-community/gmail-manager-community/issues/42
is still the issue.
Somewhere along the way, I discovered a way in the Google account settings
to _Turn ON access for less secure apps_ which helped fix the non-GMC
related issue of K9-Mail (for Android) getting fetch errors from my Android
device. Someday, Google may consider Firefox/GMC to be a "less secure app".

If anyone reading this is a Dev: Thanks for all your efforts and good work.
It is a shame Google is not as community-oriented as you are.

**Comment by ath0mas** [comment]
No more "Google Couldn't sign you in" issue
See #45 for broken **1-click auto-connect**

**Comment by gowthamds** [comment]
I'm also having the same issue 
.. "Google couldn't verify it's you, so you can't sign in to this account right now." 

Please anyone help me with this!!!
