### ISSUE TITLE
Icons Disappear From AddonBar

### ISSUE THREAD

**Issue by SeberHusky** [gmail-manager-community/gmail-manager-community#5]
With the newest patch installed (Release 0.6.5.3-2: Quick fix browser freeze), the icons would disappear from the addon bar any time settings were changed, and now they have disappeared altogether from the addon bar and the customize menu list as well.

**Comment by ath0mas** [comment]
Which Firefox version?
Addon bar is only available through external addon now. Do you have it installed or is it Personal bar instead?

As a default behavior for me, grey icon is visible in personal bar first, and when adding new account, it disappear with error in Browser console:
`gmanager-toolbar-item-<mymail>@gmail.com is too big (144px wide), moving to the palette toolbar.xml:497:0`
And indeed `toolbar.xml` defines `const kItemMaxWidth = 100`
But, loading icon with new mail label is still available in Customize panel
Can you test "workflow" again? to give more details or screens

**Comment by SeberHusky** [comment]
I mean the bar where the address bar is. I'm on 41.0.2. 

There is no gray mail icon. This happened after I added all my accounts to it. I can't get screenshots as there is nothing to show. It's not displayed in the addon bar or the customize menu.

**Comment by SeberHusky** [comment]
OK. I uninstalled the addon, then reinstalled it from Mozilla AddOns, and then I overwrote it with the patch from the XPI. I have it back.

**Comment by SeberHusky** [comment]
I have 3 gmail accounts, and it still resets to only displaying one every time I restart the browser.

**Comment by SeberHusky** [comment]
And then they all disappear and revert to the Customize tool menu whenever I exit the settings window.

**Comment by ath0mas** [comment]
Can you check in Browser Console (Ctrl+Shift+J) if you have log about widget size? like this
`gmanager-toolbar-item-<mymail>@gmail.com is too big (144px wide), moving to the palette toolbar.xml:497:0`
when you exit settings window

**Comment by SeberHusky** [comment]
This is what I get:

gmanager: toolbar destructor (gmanager-toolbar-item-[email]@gmail.com)
gmanager-toolbar-item-[email]@gmail.com is too big (146px wide), moving to the palette toolbar.xml:497:0
[CustomizableUI] Widget gmanager-toolbar-item-[email]@gmail.com not found, unable to remove from nav-bar CustomizableUI.jsm:171
gmanager: toolbar destructor (gmanager-toolbar-item-[email]@gmail.com)
gmanager-toolbar-item-[email]@gmail.com is too big (111px wide), moving to the palette toolbar.xml:497:0
[CustomizableUI] Widget gmanager-toolbar-item-[email]@gmail.com not found, unable to remove from nav-bar CustomizableUI.jsm:171
gmanager: toolbar destructor (gmanager-toolbar-item-[email]@gmail.com)

**Comment by SeberHusky** [comment]
I should note I've used this addon for 2 or 3 years since it was patched after being abandoned, and I never had this issue before.

**Comment by ath0mas** [comment]
As error message tells, it is a normal behavior/size restriction set by Firefox UI.
And it is not new, icon already jumped in previous patched versions... it is not linked to any changes in addon, but Firefox UI itself.

We should find a way to prevent addon icon from "jumping" when too large

**Comment by SeberHusky** [comment]
Hey, just letting you know that I fixed it. 

I found this post here: https://addons.mozilla.org/en-US/firefox/addon/gmail-manager-ng/reviews/584946/

**Comment by ath0mas** [comment]
Great! I close issue so.

**Comment by ath0mas** [comment]
Reopened in #22 and fixed then
