### ISSUE TITLE
No Notification On New Labels

### ISSUE THREAD

**Issue by SeberHusky** [gmail-manager-community/gmail-manager-community#52]
I am not getting notifications for new mail that is under other labels besides the main inbox. Not sure what the issue is, if its on my end or yours,

**Comment by SeberHusky** [comment]
Now I'm not getting any new notifications, period. Not sure, might be a cookies issue?

**Comment by Endor8** [comment]
Take a look here, I think this is the same issue:
#51

**Comment by ath0mas** [comment]
0.7.2 released, please update
Confirm issue can be closed?

**Comment by SeberHusky** [comment]
Seems to be working OK now, yes.
