### ISSUE TITLE
Can't install on newer Firefox due to being unsigned.

### ISSUE THREAD

**Issue by bacon-cheeseburger** [gmail-manager-community/gmail-manager-community#56]
Recent versions (49 and newer iirc) of Firefox will not allow installation of an unsigned extension/addon. Previously you could bypass this by setting xpinstall.signatures.required to false but that config option is now deprecated. The only alternatives I'm aware of are using the developer or unbranded versions of Firefox. To use the addon with new Mozilla Firefox, it will have to be signed from here on out.

**Comment by ath0mas** [comment]
Since November 2015 this addon is available on AMO (signed, auto-update, ...) and current version works fine on Firefox 53
You should install it from https://addons.mozilla.org/fr/firefox/addon/gmail-manager-community/

which version do you use?

**Comment by bacon-cheeseburger** [comment]
I mentioned this because I didn't see any mention of AMO anywhere. The .xpi is available but with limited install options. Maybe host the signed xpi instead?
