### ISSUE TITLE
Problem with encoding to Unicode

### ISSUE THREAD

**Issue by iHastr** [gmail-manager-community/gmail-manager-community#7]
Cyrillic symbols in the title of a popup window are displayed incorrectly!
For details see my comment here:
https://github.com/gmail-manager-community/gmail-manager-community/issues/4#issuecomment-151777083
This issue was in the original addon from AMO.
It's easy to fix. Just need to open the file
`"chrome\gmanager.jar\content\overlayToolbarTooltip.js"`
Modify function "createLabel" and convert strings to Unicode separately.
Change the following lines:
`Line 50: label.setAttribute("value", aValue);`
// Account Email
`Line 69: el = this._createLabel(gmanager_Utils.toUnicode(aAccount.alias));`
// Label Name
`Line 127: elRow.appendChild(this._createLabel(gmanager_Utils.toUnicode(label.name)));`
`Line 170: el = this._createLabel(gmanager_Utils.toUnicode(snippets[i].from) + " > " + gmanager_Utils.toUnicode(snippets[i].subject));`
`Line 176: el = this._createLabel(gmanager_Utils.toUnicode(snippets[i].date));`

That's all! Now all labels are displayed correctly.

Also translation into other languages is outdated, in particular Russian. And I have a corrected version of the locale ru-RU. Can I attach it here?

**Comment by ath0mas** [comment]
You can't attach file directly.
So, visit files inside https://github.com/gmail-manager-community/gmail-manager-community/tree/master/src/chrome/locale/ru-RU
and for those you want to contribute to, click on the pen icon (top right) to "Edit the file in your fork of this project"
Validate your changes, and finally create a Pull Request from your changes

**Comment by iHastr** [comment]
OK, done! If I'm not mistaken about "Pull Request".

Also in the file **install.rdf** need to add the following block:
        `<em:localized>`
            `<Description>`
            `<em:locale>ru-RU</em:locale>`
            `<em:name>Gmail Manager NG</em:name>`
            `<em:description>Форк Gmail Manager для управления несколькими аккаунтами Gmail и получения уведомлений о новой почте. Основан на разработках Gmail Manager от Todd Long, который, по-видимому, прекратил поддержку дополнения.</em:description>`
            `<em:creator>Erik Nedwidek</em:creator>`
            `<em:contributor>Todd Long</em:contributor>`
            `<em:translator>Капелька Яда</em:translator>`
            `</Description>`
        `</em:localized>`

**Comment by iHastr** [comment]
Pre-release 0.6.5.3-3.beta.3 - Now it works fine!
But the names of accounts with Unicode symbols are unreadable.
![22](https://cloud.githubusercontent.com/assets/1679304/10813772/61d99a74-7e32-11e5-997e-93060d7cc009.png)
These are accounts that have allowed "importing emails"
https://support.google.com/mail/answer/21289?hl=en
And I don't know how to fix their encoding.

**Comment by ath0mas** [comment]
Can you please copy the label name here for us to test with it too?
My first checks with Cyrillic letters showed no difference with default Firefox display... some letters do not render (like [here](https://en.wikipedia.org/wiki/Cyrillic_script_in_Unicode#Mordvin_letters))
Initially written in cyrillic (not unicode) and is ok? Maybe linked to cyrillic in unicode :grey_question:

**Comment by ath0mas** [comment]
Comparing your 2 screens (https://github.com/gmail-manager-community/gmail-manager-community/issues/4#issuecomment-151777083, 2 days ago, and https://github.com/gmail-manager-community/gmail-manager-community/issues/7#issuecomment-152114693, today), it seems nothing changed about labels names display :cry: while we added `gmanager_Utils.toUnicode(label.name)`

In Browser Console, you should see a line "x labels(s) were found", and then
`label.name + " (" + label.unread + (label.total > 0 ? " of " + label.total : "") + ")"`
Is label name correct here in the log?
Any log message like "Error converting to unicode:"? With which exception?

**Comment by ath0mas** [comment]
\+ @iHastr see #13: removed em:localized, because already defined in locale, and your name moved up ; inside beta.4

**Comment by iHastr** [comment]
Label name, for example:
`Капелька`
or
`Проверка`
In the log label name is correct. No errors like "Error converting to unicode:".
2 years ago I was looking for the cause of incorrect encoding, but never found.

**Comment by ath0mas** [comment]
When I log label name values inside `overlayToolbarTooltip.js`, I get:

```
gmanager: ----- label name: "Капелька"
gmanager: ----- label name unicode: "\u001a0?5;L:0"
```

so `label.name` is already correct, and using `gmanager_Utils.toUnicode()`on it, breaks value to add

... when reverting the change on line 127 you suggested initially, it's seems to be ok

**Comment by ath0mas** [comment]
@iHastr hope new [0.6.5.3-3.beta.5](https://github.com/gmail-manager-community/gmail-manager-community/releases/tag/0.6.5.3-3.beta.5) fixes label name for you too
yes? please :smile:

**Comment by iHastr** [comment]
Yes! Everything is fine! Thanks! You can release the Final I hope.
![ok](https://cloud.githubusercontent.com/assets/1679304/10855550/4251bf48-7f53-11e5-9acd-7b814af9aae7.png)
Have a nice weekend! Take care! :smile:

**Comment by ath0mas** [comment]
Great :v:
